version: '2'
services:
  db:
    image: postgres:9.5
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=haustuer
      - POSTGRES_DB=haustuer
      - POSTGRES_PASSWORD=haustuer
  service:
    build: .
    image: netzgruen/haustuerapp-services
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    links:
      - db
  ui:
    # build before - other repo
    image: netzgruen/haustuerapp-ui
  reverseproxy:
    image: nginx:1.13
    ports:
      - 80:80
    links:
      - service
      - ui
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
